# Ignore the package manager database, aconfmgr already get its own list of packages
IgnorePath '/var/lib/pacman/*'

# Ignore all Flatpak data (apps, runtimes, etc.), they are selfcontained
IgnorePath '/var/lib/flatpak/*'

# Other common high-churn directories you likely want to ignore:
IgnorePath '/var/cache/*'
IgnorePath '/var/log/*'
IgnorePath '/var/tmp/*'
IgnorePath '/run/*'
IgnorePath '/dev/*'
IgnorePath '/proc/*'
IgnorePath '/sys/*'
IgnorePath '/tmp/*'
IgnorePath '/mnt/*'

# linux kernel
IgnorePath '/boot/vmlinuz-linux'
# RAM image at boot
IgnorePath '/boot/initramfs-linux.img'
IgnorePath '/boot/initramfs-linux-fallback.img'

IgnorePath '/boot/EFI/BOOT/BOOTX64.EFI' # Generated, used by the os for instructions on booting
IgnorePath '/boot/amd-ucode.img' # managed by amd-ucode
IgnorePath '/boot/grub/*' # managed by grub

# Generated by update-ca-trust
IgnorePath '/etc/ca-certificates/extracted/cadir/\*'

# This are generated when you install a font
IgnorePath '/etc/fonts/conf.d/\*'

# This files get update when you install/remove software and are all generated
IgnorePath '/usr/share/mime/*'

# Icon caches
IgnorePath '/usr/share/icons/*/icon-theme.cache'

# Desktop file caches
IgnorePath '/usr/share/applications/mimeinfo.cache'

# clamav virus definition, get updated by clamav
IgnorePath '/var/lib/clamav/main.cld'
# Daily update of the above
IgnorePath '/var/lib/clamav/daily.cvd'

# Index of filesystem
IgnorePath '/var/lib/plocate/plocate.db'

# This are current process socket connections, get created and eliminated constantly
IgnorePath '/etc/pacman.d/gnupg/S.*'

# Generated by udevadm hwdb --update, all know hardware devices
IgnorePath '/usr/lib/udev/hwdb.bin'

# Generated, record certs
IgnorePath '/etc/ssl/certs/*'

# These are used for rootless containers
IgnorePath '/etc/subgid'

# It grants your user malklera permission to run commands as sudo
IgnorePath '/etc/sudoers.d/00_malklera'

# Ignore systemd D-Bus aliases (use AddService instead)
IgnorePath '/etc/systemd/system/dbus-org.freedesktop.*'

# Ignore systemd "wants" symlinks (managed by AddService)
IgnorePath '/etc/systemd/system/*.wants/*'
IgnorePath '/etc/systemd/system/autovt@.service' # appear after the first apply
IgnorePath '/etc/systemd/user/*.wants/*'

IgnorePath '/etc/.updated' # It tells the system the last time the /etc or /usr directories were updated
IgnorePath '/etc/userdb' # It's a modern way for Linux to handle user information beyond the old /etc/passwd file

IgnorePath '/usr/lib/debug/*' # debug symbols, they are generated by their respective applications

IgnorePath '/usr/lib/*.cache' # ignore cache
IgnorePath '/usr/lib/graphviz/config*' # generated plugin configuration
IgnorePath '/usr/lib/gtk-3.0/*/immodules.cache'
IgnorePath '/usr/lib/gtk-4.0/*'
IgnorePath '/usr/lib/jvm/default'
IgnorePath '/usr/lib/jvm/default-runtime'

IgnorePath '/usr/lib/locale/locale-archive' # I already track my locale
IgnorePath '/usr/lib/luarocks/rocks-5.1/manifest' # generated by luarocks with luarocks install [package]
IgnorePath '/usr/lib/modules/*' # kernel modules, get update when the kernel updates and other times
IgnorePath '/usr/lib/udev/hwdb.bin' # hardware db
IgnorePath '/usr/share/glib-2.0/schemas/gschemas.compiled' # generated by gtk apps
IgnorePath '/usr/share/info/dir' # generated for man pages
IgnorePath '/usr/share/vim/vimfiles/doc/tags' # generated vim docs
IgnorePath '/var/db/sudo/lectured/*' # the message when you first run sudo
IgnorePath '/var/lib/BrlAPI' # for braille
IgnorePath '/etc/brlapi.key' # for braille
IgnorePath '/var/lib/brltty' # for braille
IgnorePath '/var/lib/clamav/*' # manage by clamav
IgnorePath '/etc/machine-id' # generated machine specify
IgnorePath '/var/lib/dbus/machine-id' # generated machine specify
IgnorePath '/var/lib/lastlog/lastlog2.db' # generated change constantly
IgnorePath '/var/lib/libuuid' # system managed
IgnorePath '/var/lib/machines' # system managed
IgnorePath '/var/lib/NetworkManager/*' # current state by NetworkManager
IgnorePath '/var/lib/os-prober/labels' # list of OS in the system
IgnorePath '/var/lib/plocate/plocate.db' # index of files in the OS
IgnorePath '/var/lib/portables' # controled by systemd
IgnorePath '/var/lib/private' # controled by systemd
IgnorePath '/var/lib/rpcbind' # State information for the Remote Procedure Call binder (used for things like NFS network drives).
IgnorePath '/var/lib/systemd/*' # generated and managed by systemd, all temporary
IgnorePath '/var/lib/tpm2-tss' # hardware dependent
IgnorePath '/var/.updated' # generated, change each time the system state change
IgnorePath '/etc/pacman.d/gnupg/*' # managed by pacman-key
IgnorePath '/usr/bin/groupmems' # managed by shadow
IgnorePath '/usr/lib/utempter/utempter' # managed by libutempter
IgnorePath '/var/lib/systemd/timesync' # managed by systemd/TPM hook
IgnorePath '/var/lib/swtpm-localca' # managed by systemd/TPM hook
IgnorePath '/etc/audit' # managed by audit
IgnorePath '/etc/audisp' # managed by audit
IgnorePath '/etc/ca-certificates' # managed by ca-certificates
IgnorePath '/etc/fonts/conf.d/*' # managed by packages and fontconfig
# Ignore system-generated backups of user/group files
IgnorePath '/etc/group-'
IgnorePath '/etc/gshadow'
IgnorePath '/etc/gshadow-'
IgnorePath '/etc/passwd-'
IgnorePath '/etc/shadow-'
IgnorePath '/etc/passwd'
IgnorePath '/etc/passwd-'
IgnorePath '/etc/shadow'
IgnorePath '/etc/shadow-'
IgnorePath '/etc/ld.so.cache' # binary library cache
IgnorePath '/etc/os-release' # standard OS identification
IgnorePath '/etc/fstab' # current state of my disk
IgnorePath '/etc/hostname' # do not actually care to keep this
IgnorePath '/etc/.pwd.lock' # prevent multiple programs from changing passwords at the same time
IgnorePath '/etc/subuid-' # backup of subuid
IgnorePath '/etc/subgid' # This is used for rootless containers
IgnorePath '/etc/subgid-' # backup of subgid
IgnorePath '/etc/pacman.d/mirrorlist' # managed by reflector
IgnorePath '/etc/resolv.conf' # managed by my network manager
IgnorePath '/etc/systemd/user/pipewire-session-manager.service' # managed by pipewire
IgnorePath '/usr/share/zsh/*' # completion for zsh by pacman-contrib
