# This are needed for building other packages
IgnorePackage 'appstream-glib'
IgnorePackage 'blueprint-compiler'
IgnorePackage 'clang'
IgnorePackage 'gomi-debug'
IgnorePackage 'libliftoff'
IgnorePackage 'libwireplumber'
IgnorePackage 'meson'
IgnorePackage 'python-sphinx'
IgnorePackage 'tlrc-debug'

IgnorePath '/run/*'
IgnorePath '/dev/*'
IgnorePath '/proc/*' # current running process
IgnorePath '/sys/*'
IgnorePath '/tmp/*' # temporary files
IgnorePath '/mnt/*' # common mount point

IgnorePath '/boot/vmlinuz-linux'           # linux kernel
IgnorePath '/boot/vmlinuz-linux-lts'       # linux kernel lts
IgnorePath '/boot/initramfs-linux.img'     # RAM image at boot
IgnorePath '/boot/initramfs-linux-lts.img' # RAM image for lts
IgnorePath '/boot/initramfs-linux-fallback.img'
IgnorePath '/boot/EFI/BOOT/BOOTX64.EFI' # Generated, used by the os for instructions on booting
IgnorePath '/boot/amd-ucode.img'        # managed by amd-ucode
IgnorePath '/boot/grub/*'               # managed by /etc/default/grub and $ sudo grub-mkconfig -o /boot/grub/grub.cfg

IgnorePath '/etc/pacman.d/gnupg/S.*'                    # This are current process socket connections, get created and eliminated constantly
IgnorePath '/etc/pacman.d/gnupg/*'                      # managed by pacman-key
IgnorePath '/etc/ca-certificates/extracted/cadir/\*'    # Generated by update-ca-trust
IgnorePath '/etc/fonts/conf.d/\*'                       # This are generated when you install a font
IgnorePath '/etc/ssl/certs/*'                           # Generated, record certs
IgnorePath '/etc/subgid'                                # These are used for rootless containers
IgnorePath '/etc/sudoers.d/00_malklera'                 # It grants your user malklera permission to run commands as sudo
IgnorePath '/etc/systemd/system/dbus-org.freedesktop.*' # Ignore systemd D-Bus aliases (use AddService instead)
IgnorePath '/etc/systemd/system/autovt@.service'        # this is for the getty terminal, autogenerated
IgnorePath '/etc/.updated'                              # It tells the system the last time the /etc or /usr directories were updated
IgnorePath '/etc/userdb'                                # It's a modern way for Linux to handle user information beyond the old /etc/passwd file
IgnorePath '/etc/brlapi.key'                            # for braille
IgnorePath '/etc/machine-id'                            # generated machine specify
IgnorePath '/etc/audit'                                 # managed by audit
IgnorePath '/etc/audisp'                                # managed by audit
IgnorePath '/etc/ca-certificates'                       # managed by ca-certificates
IgnorePath '/etc/fonts/conf.d/*'                        # managed by packages and fontconfig
IgnorePath '/etc/group-'                                # Ignore system-generated backups of user/group files
IgnorePath '/etc/gshadow'
IgnorePath '/etc/gshadow-'
IgnorePath '/etc/passwd-'
IgnorePath '/etc/shadow-'
IgnorePath '/etc/passwd'
IgnorePath '/etc/passwd-'
IgnorePath '/etc/shadow'
IgnorePath '/etc/shadow-'
IgnorePath '/etc/ld.so.cache'                                       # binary library cache
IgnorePath '/etc/os-release'                                        # standard OS identification
IgnorePath '/etc/fstab'                                             # current state of my disk
IgnorePath '/etc/hostname'                                          # do not actually care to keep this
IgnorePath '/etc/.pwd.lock'                                         # prevent multiple programs from changing passwords at the same time
IgnorePath '/etc/subuid-'                                           # backup of subuid
IgnorePath '/etc/subgid'                                            # This is used for rootless containers
IgnorePath '/etc/subgid-'                                           # backup of subgid
IgnorePath '/etc/pacman.d/mirrorlist'                               # managed by reflector
IgnorePath '/etc/resolv.conf'                                       # managed by my network manager
IgnorePath '/etc/systemd/user/pipewire-session-manager.service'     # managed by pipewire
IgnorePath '/etc/mkinitcpio.conf.pacnew'                            # generated? by $ mkinitcpio -P
IgnorePath '/etc/pacman.d/mirrorlist.pacnew'                        # Generated
IgnorePath '/etc/shells'                                            # list of valid shells
IgnorePath '/etc/subuid'                                            # This is used for rootless containers
IgnorePath '/etc/default/grub'                                      # grub config, edit and use grub-mkconfig to apply
IgnorePath '/etc/systemd/system/getty@tty1.service.d/override.conf' # Set auto-login for malklera
IgnorePath '/etc/systemd/zram-generator.conf'                       # Configuration for zRAM
IgnorePath '/etc/systemd/system/multi-user.target.wants/postgresql.service'
IgnorePath '/etc/vconsole.conf'                    # keyboard config for tty, controled by localectl
IgnorePath '/etc/X11/xorg.conf.d/00-keyboard.conf' # keyboard configs, controled by localectl

IgnorePath '/usr/bin/groupmems'        # managed by shadow
IgnorePath '/usr/lib/debug/*'          # debug symbols, they are generated by their respective applications
IgnorePath '/usr/lib/*.cache'          # ignore cache
IgnorePath '/usr/lib/graphviz/config*' # generated plugin configuration
IgnorePath '/usr/lib/gtk-3.0/*/immodules.cache'
IgnorePath '/usr/lib/gtk-4.0/*'
IgnorePath '/usr/lib/jvm/default'
IgnorePath '/usr/lib/jvm/default-runtime'
IgnorePath '/usr/lib/locale/locale-archive'                # I already track my locale
IgnorePath '/usr/lib/luarocks/rocks-5.1/manifest'          # generated by luarocks with luarocks install [package]
IgnorePath '/usr/lib/modules/*'                            # kernel modules, get update when the kernel updates and other times
IgnorePath '/usr/lib/udev/hwdb.bin'                        # Generated by udevadm hwdb --update, all know hardware devices
IgnorePath '/usr/lib/utempter/utempter'                    # managed by libutempter
IgnorePath '/usr/lib/libvsscript.so'                       # utility to make video effects
IgnorePath '/usr/share/glib-2.0/schemas/gschemas.compiled' # generated by gtk apps
IgnorePath '/usr/share/info/dir'                           # generated for man pages
IgnorePath '/usr/share/vim/vimfiles/doc/tags'              # generated vim docs
IgnorePath '/usr/share/zsh/*'                              # completion for zsh by pacman-contrib
IgnorePath '/usr/share/fish/*'                             # completion for fish
IgnorePath '/usr/share/mime/*'                             # This files get update when you install/remove software and are all generated
IgnorePath '/usr/share/icons/*/icon-theme.cache'           # Icon caches
IgnorePath '/usr/share/applications/mimeinfo.cache'        # Desktop file caches
IgnorePath '/usr/share/xkeyboard-config-2/symbols/custom'  # custom keymap, controled by localectl
IgnorePath '/usr/share/pkgconfig/hyprland.pc'              # generated by hyprland?
IgnorePath '/usr/local/share/kbd/keymaps/es.map.gz'        # more custom keymap? which is the root?, this is a gzip file, i do not put it there, has to be generated

IgnorePath '/var/cache/*'
IgnorePath '/var/log/*'
IgnorePath '/var/tmp/*'
IgnorePath '/var/.updated'                # generated, change each time the system state change
IgnorePath '/var/db/sudo/lectured/*'      # the message when you first run sudo
IgnorePath '/var/lib/BrlAPI'              # for braille
IgnorePath '/var/lib/brltty'              # for braille
IgnorePath '/var/lib/clamav/*'            # manage by clamav
IgnorePath '/var/lib/dbus/machine-id'     # generated machine specify
IgnorePath '/var/lib/lastlog/lastlog2.db' # generated change constantly
IgnorePath '/var/lib/libuuid'             # system managed
IgnorePath '/var/lib/machines'            # system managed
IgnorePath '/var/lib/NetworkManager/*'    # current state by NetworkManager
IgnorePath '/var/lib/os-prober/labels'    # list of OS in the system
IgnorePath '/var/lib/plocate/plocate.db'  # index of files in the OS
IgnorePath '/var/lib/portables'           # controled by systemd
IgnorePath '/var/lib/private'             # controled by systemd
IgnorePath '/var/lib/rpcbind'             # State information for the Remote Procedure Call binder (used for things like NFS network drives).
IgnorePath '/var/lib/systemd/*'           # generated and managed by systemd, all temporary
IgnorePath '/var/lib/tpm2-tss'            # hardware dependent
IgnorePath '/var/lib/systemd/timesync'    # managed by systemd/TPM hook
IgnorePath '/var/lib/swtpm-localca'       # managed by systemd/TPM hook
IgnorePath '/var/lib/pacman/*'            # Ignore the package manager database, aconfmgr already get its own list of packages
IgnorePath '/var/lib/flatpak/*'           # Ignore all Flatpak data (apps, runtimes, etc.), they are selfcontained
IgnorePath '/var/lib/clamav/main.cld'     # clamav virus definition, get updated by clamav
IgnorePath '/var/lib/clamav/daily.cvd'    # Daily update of the above
IgnorePath '/var/lib/plocate/plocate.db'  # Index of filesystem
IgnorePath '/var/lib/postgres/*'          # Postgress related data

IgnorePath '/.snapshots/*' # snapshots are only for backup recovery
