#!/usr/bin/env zsh

autoload -Uz colors && colors

alias python="python3"

# Enable color support for ls and add handy aliases
if [[ -x /usr/bin/dircolors ]]; then
    if [[ -r ~/.config/zsh/.dircolors ]]; then
        eval "$(dircolors -b ~/.config/zsh/.dircolors)"
    else
        eval "$(dircolors -b)"
    fi

    alias ls='ls -F --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias btop="btop -p 1"
alias mv="mv -i"
alias cp="cp -i"
alias sqlite='sqlite3 -init <(echo ".mode box")'
alias yazi="flatpak run io.github.sxyazi.yazi"
